// Frases próprias do Gyn Flow sobre constância, treino, descanso e autocuidado. Sem citação de
// gente famosa e sem culpa: a ideia é acompanhar, não cobrar. Todas cabem em 140 caracteres, o
// mesmo limite da frase que a pessoa escreve.
export const phrases: readonly string[] = [
  'Constância vale mais que intensidade. Um pouco hoje, de novo amanhã.',
  'Descansar também é parte do treino.',
  'O treino de hoje não precisa ser o melhor. Só precisa acontecer.',
  'Dormir bem é o suplemento mais barato que existe.',
  'Progresso é a soma de dias comuns.',
  'Você não precisa de motivação todo dia. Precisa de um horário.',
  'Beba água antes de sentir sede.',
  'Cada série feita é uma a menos até o próximo recorde.',
  'Dia sem energia? Treino leve também conta.',
  'Alongar cinco minutos hoje poupa semanas depois.',
  'Comparar-se com quem você era ontem é mais justo que com qualquer outra pessoa.',
  'A carga sobe devagar. O hábito também.',
  'Faltar um dia não apaga uma semana.',
  'Recorde não é só carga: é aparecer quando ninguém está vendo.',
  'Respirar fundo entre as séries é técnica, não fraqueza.',
  'Água, sono e paciência: a base de todo bom treino.',
  'Sua evolução não precisa caber numa foto para existir.',
  'O corpo aprende com repetição, não com pressa.',
  'Descanso planejado é diferente de desistência.',
  'Um treino curto e bem feito vale mais que um longo e distraído.',
  'Cuidar da postura fora da academia também é treino.',
  'Nem todo dia é dia de recorde. Tudo bem.',
  'Seu ritmo é o único que precisa fazer sentido para você.',
  'Aquecer bem é a parte do treino que ninguém posta, mas todo mundo sente.',
  'O melhor horário para treinar é o que você consegue manter.',
  'Ouvir o corpo é parte da técnica.',
  'Comer bem não é castigo. É combustível.',
  'Sem pressa: músculo se constrói em meses, não em posts.',
  'Anotar o treino é conversar com quem você vai ser daqui a três meses.',
  'Uma semana ruim é só uma semana.',
  'Sete horas de sono fazem mais pelo treino do que a série extra.',
  'Você já treinou mais vezes do que lembra. Isso conta.',
  'Cargas pequenas, muitas semanas: é assim que se fica forte.',
  'Hoje pode ser só uma caminhada. Também é movimento.',
  'Treino não é dívida. Não precisa pagar o dia perdido em dobro.',
  'Amanhã começa com o que você fez hoje. Um pouco basta.',
  'A técnica vem antes da carga. Sempre.',
  'Não é sobre ter tempo. É sobre reservar vinte minutos.',
  'Descansar sem culpa faz parte do plano.',
  'Garrafa cheia, música boa e a primeira série. O resto vem.',
  'Treino difícil hoje é treino normal daqui a um mês.',
  'Constância é fazer o simples de novo, mesmo sem vontade.',
  'Corpo cansado pede pausa. Mente cansada, às vezes, pede movimento.',
  'Um passo por dia também é caminhada longa.',
  'Não existe atraso aqui. Existe o seu tempo.',
  'Registrar o treino é a parte que dura mais que o treino.',
  'Trocar "preciso" por "escolho" muda o treino inteiro.',
  'Voltar depois de uma pausa é a parte mais difícil. Você já está fazendo.',
];
